server:
  port: 8888
  
spring:
  application:
    name: hr-config-server
    
  cloud:
   config:
     server:
       git:
         default-label: master
         uri: https://github.com/lucasnpires/microservices-java-config