server:
  port: 8765

spring:
  application:
    name: hr-api-gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000

zuul:
  routes:
    hr-worker:
      service-id: hr-worker
      path: /hr-worker/**
    hr-payroll:
      service-id: hr-payroll
      path: /hr-payroll/**